Task 1 — Clean the Data
Using the synthetic dataset below, write Python code to:

*Impute missing values in age with the median and in  city with the mode

*Remove any duplicate rows

In [27]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

In [28]:
df['age'] = df['age'].fillna(df['age'].median())

df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4  35.0  Mumbai    Male         120000
4            2  35.0   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [29]:
df['city'] = df['city'].fillna(df['city'].mode()[0])
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
4            2  35.0   Delhi  Female          80000
5            5  40.0   Delhi    Male          95000

In [30]:
removing_dup = df.drop_duplicates().reset_index(drop=True)
removing_dup

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
4            5  40.0   Delhi    Male          95000

Task 2 — Encode Categorical Columns

After cleaning, encode the categorical columns:

Apply One-Hot Encoding to city

Apply Label Encoding to gender

Print the resulting dataframe.

In [31]:
from sklearn.preprocessing import LabelEncoder
df = pd.get_dummies(df, columns=['city'],prefix='city')
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])
df

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       1          40000       False         True
1            2  35.0       0          80000        True        False
2            3  35.0       0          60000        True        False
3            4  35.0       1         120000       False         True
4            2  35.0       0          80000        True        False
5            5  40.0       1          95000        True        False

Task 3 — Scale Numerical Features
Scale age and annual_income using both methods below on the cleaned dataframe, and print the results of each:

Min-Max Scaling (using MinMaxScaler)

Standardisation (using StandardScaler)

In 2–3 sentences, explain when you would prefer one over the other.

In [37]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
print("Min-Max Scaling")
clos_to_scale = ['age', 'annual_income']
mms = MinMaxScaler()
df_minmax = df.copy()
df_minmax[clos_to_scale] = mms.fit_transform(df_minmax[clos_to_scale])
print(df_minmax[clos_to_scale])

print("\nStandardization")
ss = StandardScaler()
df_standardized = df.copy()
df_standardized[clos_to_scale] = ss.fit_transform(df_standardized[clos_to_scale])
print(df_standardized[clos_to_scale])

Min-Max Scaling
        age  annual_income
0  0.000000         0.0000
1  0.666667         0.5000
2  0.666667         0.2500
3  0.666667         1.0000
4  0.666667         0.5000
5  1.000000         0.6875

Standardization
        age  annual_income
0 -2.042649      -1.552077
1  0.185695       0.033023
2  0.185695      -0.759527
3  0.185695       1.618123
4  0.185695       0.033023
5  1.299867       0.627435